### ISSUE TITLE
WebApp wont open

### ISSUE THREAD

**Issue by VenoPhage** [brian91292/ChatCore#13]
i've completely re downloaded the game restarted and everything and yet the web app to set this up refuses to open

**Comment by Uncle-Taco** [comment]
same issue here. it is driving me insane

**Comment by smyalygames** [comment]
I'm not too sure where the settings are kept, because I think somewhere within AppData, but I found out that the WebApp link is just [http://localhost:8338/](url). So just open up Beat Saber to the menu, and go onto that link.
