### ISSUE TITLE
WebApp not opening

### ISSUE THREAD

**Issue by gustavodiel** [brian91292/ChatCore#4]
- **Game Version**: 1.9.0
- **ChatCore Version**: v1.0.0 RC3

I installed so that the folder structure is like
```
BeatSaber/
    - Libs/
        - ChatCore.dll
     - Plugins/
        - ChatCore.manifest
```

Also I've searched the logs for `ChatCore` and found this:
```
[DEBUG @ 18:14:25 | IPA/Loader] Adding info for bare manifest ChatCore.manifest
...
[INFO @ 18:14:26 | IPA] ChatCore (ChatCore): 1.0.0-rc3
...
[DEBUG @ 18:14:26 | IPA/Updater] Phantom Dependency: ChatCore@1.0.0-rc3 - (>=1.0.0-rc3 ! ) 
```

The full log can be found here: https://pastebin.com/K9nc4BCf

**Comment by brian91292** [comment]
Have you installed the new enhanced stream chat? No web ui will appear unless another assembly/mod actually uses chat core.

**Comment by gustavodiel** [comment]
Yup, working now! Thanks
